---

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Copy ufw config
  copy:
    src: "{{ item }}"
    dest: /etc/ufw/{{ item }}
    force: yes
  with_items:
    - user.rules
    - user6.rules
  notify: Reload ufw


- name: Enable firewall
  service:
    name: ufw
    enabled: yes

- name: start firewall
  service:
    name: ufw
    state: started
